---
- name: Поиск по employeeID
  hosts: localhost
  gather_facts: no
  vars:
    admin_login: "{{ login }}"
    admin_password: "{{ password }}"
    employee_id: "{{ empid }}"
  tasks:

    - name: Сформировать команду в переменной
      set_fact:
        cmd_args: "{{ admin_login }} '{{ admin_password }}' {{ employee_id }}"

    - name: Запустить скрипт через Ansible script
      script: search_by_employeeid.sh {{ cmd_args }}
      register: result

    - name: Показать результат
      debug:
        var: result.stdout_lines
