---
- name: Поиск по employeeID
  hosts: localhost
  gather_facts: no
  vars:
    admin_login: "{{ login }}"
    admin_password: "{{ password }}"
    employee_id: "{{ empid }}"
  tasks:

    - name: Показать текущую директорию
      shell: pwd
      register: current_dir

    - debug:
        msg: "Рабочая директория: {{ current_dir.stdout }}"

    - name: Показать список файлов
      shell: ls -l
      register: file_list

    - debug:
        var: file_list.stdout_lines

    - name: Показать параметры
      debug:
        msg:
          - "Login: {{ admin_login }}"
          - "EmpID: {{ employee_id }}"

    - name: Запустить скрипт поиска
      shell: ./search_by_employeeid.sh {{ admin_login }} "{{ admin_password }}" {{ employee_id }}
      register: result

    - name: Показать результат
      debug:
        var: result.stdout_lines
